#!/bin/bash

set -x

C3PO=c3po-0.20.42

VERSION=1.5.0

${C3PO} S.G -execVersion $VERSION -overloaded -distr -binDir '${HOME}/bin' \
-objDir objects -srcDir src  -f $* 

patch -p2 < search_range.patch
patch -p2 < util-file-cc.patch
